### ISSUE TITLE
How to include intensity data

### ISSUE THREAD

**Issue by reddittoob** [url-kaist/patchwork-plusplus#17]
Hi, I'm trying to use your amazing work.

In the data, point cloud was used only x,y,z data.

However, I want to use data including intensity data because I need to use intensity.

How can I do that?

Thank you.

**Comment by seungjae24** [comment]
Hi @reddittoob , thank you for having interest on our work.

Actually, the example data provided in the repository ( e.g., 00000*.bin ) are including x, y, z, and intensity. Also, as you can see the function `read_bin()` in the demo codes, Patchwork++ already utilizes the intensity information. ( The input pointcloud receives 4 inputs from the bin per each iteration, which are x, y, z, and intensity. )

You can follow the demo codes and modify it for your situation. If you are using ROS, I can suggest you to visit [this repository](https://github.com/url-kaist/patchwork-plusplus-ros). Thank you.

**Comment by reddittoob** [comment]
Thank you for your reply.

I already knew that intensity was already included in read_bin(), however, result only include x,y,z information like below picture.

I want to include intensity value in result data.

![Screenshot from 2022-11-29 16-40-57](https://user-images.githubusercontent.com/30588581/204468420-d7eb20c1-26f4-453e-9f41-86f6345df73c.png)

**Comment by seungjae24** [comment]
Did you modify the function `PatchWorkpp::toEigenCloud()` ? It is defined in the `patchworkpp/include/patchworkpp.h` file and declared in the `patchworkpp/src/patchworkpp.cpp` file. You should edit this function to output `Eigen::MatrixX4f`, not `Eigen::MatrixX3f`, to include the intensity information. Also, you should put x, y, z, and intensity information of points to `dst` in this function.

**Comment by reddittoob** [comment]
After I changed as you said and compile, I got errors like below.

 error: static assertion failed: YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES
   EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(ActualDstTypeCleaned,Src)

/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:833:3: error: static assertion failed: YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES

**Comment by seungjae24** [comment]
Did you check the corresponding functions, such as `getGround()`, `getNonground()`, and the corresponding variables, such as  `ground` or `nonground` in the files: demo_visualize.cpp, demo_sequential.cpp? You should change them to operate properly with Eigen::MatrixX4f format.

**Comment by reddittoob** [comment]
Can I use this in python?

When I run demo_visulaize.py, I got 

malloc(): memory corruption
Aborted (core dumped)

**Comment by seungjae24** [comment]
I make the branch adding the intensity information to the point cloud simply. Please check [this branch](https://github.com/url-kaist/patchwork-plusplus/tree/17-how-to-include-intensity-data). If you build the code and run the python code, the python demo codes will print out the point cloud including the intensity information. ( By the way, I prevented the visualization of point cloud in the python code of this branch because I guess that geometry::PointCloud should get the input point cloud with the format of `Eigen::MatrixX3f`. You can visualize the point cloud by making the Eigen::MatrixX3f separately. )

**Comment by reddittoob** [comment]
I solved error thanks to your help.

I really sorry, but I have more question.

Results was little different before I chaned code. Please refer below picture.

What is the problem?

![Screenshot from 2022-11-30 13-37-49](https://user-images.githubusercontent.com/30588581/204709187-038a71e4-1f30-4ad0-932e-427320afb981.png)

![Screenshot from 2022-11-30 13-38-02](https://user-images.githubusercontent.com/30588581/204709195-92c3afe9-2887-44e4-895b-e9243d6eab40.png)

**Comment by seungjae24** [comment]
Actually, it is very difficult for me to find out the exact problem of your situation because I didn't change anything from the master branch, except for the addition of intensity information.

Moreover, as you can see in the below picture, there's no difference between the provided branch and the master branch. I got the exact same result.
![image](https://user-images.githubusercontent.com/67184306/204711027-55e1b958-c030-4905-ae44-481313afb633.png)

**Comment by reddittoob** [comment]
Thank you for your help!
