### ISSUE TITLE
Have you tried Patchwork++ on nuScenes?

### ISSUE THREAD

**Issue by zwqnju** [url-kaist/patchwork-plusplus#3]
I run your program on one scene in nuScenes, but the performance is not so good as SemanticKITTI. Is it because nuScenes uses a 32-beam LiDAR and the point cloud is sparser? Do you have any suggestions to improve it?
![Screenshot from 2022-08-24 10-09-19](https://user-images.githubusercontent.com/7918902/186302038-20af0603-5db5-4688-a4d8-a835d7cd7a13.png)

**Comment by seungjae24** [comment]
Well, at first, I need to say that it is very difficult for me to say which one directly occurs such poor result because the picture is not enough to find out the problem. However, I guess that the sparsity of point cloud due to less beams won't let such result since the false positive points(red points) in your picture are dense enough to be estimated as a proper ground plane in my thought. If the divided patch is far from the sensor origin, the sparsity can be a severe factor which results in a poor plane estimation. I can suggest you to check the uprightness, elevation, and flatness values of those wrongly-estimated planes and compares that values to the thresholds of them, respectively.

**Comment by zwqnju** [comment]
> 

No..
