### ISSUE TITLE
Noise removal vs concentric zone model conversion question

### ISSUE THREAD

**Issue by GMahmoud** [url-kaist/patchwork-plusplus#44]
Hello @seungjae24

After diving in your patchwork implementation, I found some inconsistencies that make me wonder whether in some scenario swe can get duplicated point in the output point cloud. 

 I see at first the [reflected_noise_removal](https://github.com/url-kaist/patchwork-plusplus/blob/master/patchworkpp/src/patchworkpp.cpp#L393) is adding noisy points to `cloud_non_ground_`
 Then in a second time the [pc2czm](https://github.com/url-kaist/patchwork-plusplus/blob/master/patchworkpp/src/patchworkpp.cpp#L618) is pushing points outside of zones to `cloud_non_ground_`.
 
 How you can be sure that noisy points will not be duplicated with zone model conversion ? 🤔
 
 Thanks again for you great work.
 
 Cheers ! 😄

**Comment by seungjae24** [comment]
Hi @GMahmoud, thank you for interest on our work.

Actually, the z component of noisy points, which are filtered out at the reflected_noise_removal function, are manually set to the value of std::numeric_limits<float>::min(), which is not expected in usual point cloud data. Then, in the concentric zone model division, there is a conditioned part for points with the value std::numeric_limits<float>::min() to skip the for loop, which guarantee noisy points are neglected in further procedures.

Honestly, the code looks somewhat weakly constrained and needs some tight prohibition for noisy points instead of using the specific value as std::numeric_limits<float>::min(). But, it is true that the original code was also designed to skip noisy points in further procedures without any duplication.

Thank you :)
