### ISSUE TITLE
This line code confused me.

### ISSUE THREAD

**Issue by Shaoqing26** [url-kaist/patchwork-plusplus#6]
https://github.com/url-kaist/patchwork-plusplus/blob/0d430884cbea4c3cfa009cf99a46c4f04ae964e2/patchworkpp/src/patchworkpp.cpp#L97

In my opinion, i should begin with 'init_idx'?

**Comment by seungjae24** [comment]
Hi, @Shaoqing26. Thanks for sharing your opinion.

Actually, your opinion makes sense since we find the `init_idx` value to remove the noises.

The code, which finds the `init_idx` value, prevents the noise from being selected as the 'lowest point representative(LPR)' by the threshold of  `params_.adaptive_seed_selection_margin * params_.sensor_height`. Because the average height of LPR is used to calculate the height threshold of initial seed points(`lpr_height + params_.th_seeds`), LPR should exclude the noise points which have unrealistically low heights.

However, when we select the initial seed points, it is necessary to include every point with a lower height than the `lpr_height + params_.th_seeds` by beginning the for loop with 0. This is because the ground points can still exist under the `params_.adaptive_seed_selection_margin * params_.sensor_height` due to the slope of the ground. As you pointed out, the noise points can be included in the initial seed points at this moment.

By the way, to handle the problem of noises, Patchwork++ presents a new module called Reflected Noise Removal(RNR). Moreover, as there is another step for the ground points extraction using PCA, I guess this part will not affect the final ground estimation result severely whether the for loop begins with 0 or init_idx.

I will check the potential problem of this part. Thank you :)
